name = "glowcare"
type = "webpack"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-07-09"

[build]
command = "npm run build"
upload.format = "service"

[site]
bucket = ".next"
entry-point = "workers-site"
